name: Run clang-format
description: Runs clang-format and checks for any changes introduced by it
inputs:
  failCondition:
    description: Controls whether failed checks also fail the workflow run
    required: false
    default: 'never'
  workingDirectory:
    description: Working directory for checks
    required: false
    default: ${{ github.workspace }}
runs:
  using: composite
  steps:
    - name: Check Runner Operating System 🏃‍♂️
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        Write-Host "::notice::run-cmake-format action requires a macOS-based or Linux-based runner."
        Exit 2

    - name: Install .github/scripts deps (zsh) 🛍️
      if: runner.os == 'Linux'
      shell: bash
      run: |
        which zsh || sudo apt-get install -y --no-install-recommends zsh

    - name: Run clang-format 🐉
      id: result
      shell: zsh --no-rcs --errexit --pipefail {0}
      working-directory: ${{ inputs.workingDirectory }}
      env:
        GITHUB_EVENT_FORCED: ${{ github.event.forced }}
        GITHUB_REF_BEFORE: ${{ github.event.before }}
      run: |
        : Run clang-format 🐉
        if (( ${+RUNNER_DEBUG} )) setopt XTRACE

        local -a changes=($(git diff --name-only HEAD~1 HEAD))
        case ${GITHUB_EVENT_NAME} {
          pull_request) changes=($(git diff --name-only origin/${GITHUB_BASE_REF} HEAD)) ;;
          push) if [[ ${GITHUB_EVENT_FORCED} != true ]] changes=($(git diff --name-only ${GITHUB_REF_BEFORE} HEAD)) ;;
          *) ;;
        }

        if (( ${changes[(I)(*.c|*.h|*.cpp|*.hpp|*.m|*.mm)]} )) {
          echo ::group::Install clang-format-17
          brew install --quiet obsproject/tools/clang-format@17
          echo ::endgroup::

          echo ::group::Run clang-format-17
          ./build-aux/run-clang-format --fail-${{ inputs.failCondition }} --check
          echo ::endgroup::
        }
